---
name: Ansible WireGuard OpenWISP CI Build

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.distro }}
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: ubuntu2204
            ansible_interpreter: /usr/bin/python3
          - distro: ubuntu2404
            ansible_interpreter: /usr/bin/python3
          - distro: debian11
            ansible_interpreter: /usr/bin/python3
          - distro: debian12
            ansible_interpreter: /usr/bin/python3

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install python dependencies
        run: |
          pip install -U pip wheel setuptools
          pip install -r requirements-test.txt

      - name: Install Ansible Galaxy dependencies
        run: ansible-galaxy collection install "community.general:>=3.6.0"

      - name: QA checks
        run: |
          ./run-qa-checks

      - name: Tests
        run: molecule test
        env:
          ROLE_NAME: openwisp2
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
          ANSIBLE_PYTHON_INTERPRETER: ${{ matrix.ansible_interpreter }}
